/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.MouseListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class FRM_Consulta extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Consulta
     */
    public FRM_Consulta() {
        initComponents();
    }
    
     //Metodo para Llenar la tabla:
    public void setDataTable(String[][] datos, String[] encabezado)
    {
        this.jTBUsuarios.setModel(new DefaultTableModel(datos, encabezado));
        this.jScrollPane1.setViewportView(this.jTBUsuarios); //Cargar la Tabla y se vea la barra de Desplazamiento.
    }//Fin Metodo
    
    //Devuelva Titulo de lo seleccionado (Llenar espacios)
    public String[] getDataRow() {
        String[] datosUsuarios = new String[this.jTBUsuarios.getColumnCount()];
        int filaSeleccionada = this.jTBUsuarios.getSelectedRow();
        
        for(int i = 0; i < datosUsuarios.length; i++) {
            datosUsuarios[i] = this.jTBUsuarios.getValueAt(filaSeleccionada, i).toString();
        }//Fin FOR
        return datosUsuarios;
    }//Fin Metodo DataRow
    
    //Escuchar tabla cuando se seleccione
    public void escucharMouse(MouseListener manejador) {
        this.jTBUsuarios.addMouseListener(manejador);
    }//Fin Metodo escuchar Mouse

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTBUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta");

        jTBUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Nombre", "Contraseña", "Perfil"
            }
        ));
        jScrollPane1.setViewportView(jTBUsuarios);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setText("Lista de Usuarios Registrados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBUsuarios;
    // End of variables declaration//GEN-END:variables
}//Fin Class
